apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
- base/deployment.yaml
- base/rbac.yaml
- base/service.yaml

namespace: default

images:
- name: qjoly/kubernetes-coffee-image
  newTag: evil
