apiVersion: v1
kind: ServiceAccount
metadata:
  name: votre-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-list-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-list-role
subjects:
- kind: ServiceAccount
  name: votre-service-account
  namespace: default
