name: Build Docker Images

on:
  push:

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - Dockerfile: simple/Dockerfile
            tag: simple
          - Dockerfile: micro-service/Dockerfile.api
            tag: api
          - Dockerfile: micro-service/Dockerfile.frontend
            tag: frontend
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: $GITHUB_WORKSPACE/$(dirname ${{ matrix.dockerfile }})
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ matrix.tag }}
      
